version: '1.0'

services:
  openwrt-builder:
    image: openwrt-build
    pull_policy: never
    container_name: openwrt-workspace
    volumes:
      - ./workspace:/home/builder/openwrt
    user: builder
    working_dir: /home/builder/openwrt
    # stay awake in the background forever, waiting for you to log in.
    tty: true
    command: sleep infinity
