services:
  # 'kernel-engine' is the service name (label for the task)
  kernel-engine:
    build:
      context: .
      args:
        - VERSION=${VER}
    image: openwrt-kernel-${VER}
    container_name: openwrt-kernel-worker-${VER}
    volumes:
      # Maps the tiny results to your host disk automatically
      - /root/builds/${VER}:/output