services:
  # 'kernel-engine' is the service name (label for the task)
  kernel-engine:
    build:
      context: .
      args:
        - VERSION=${VER}
    image: openwrt-kernel-${VER}
    container_name: openwrt-kernel-worker-${VER}
    volumes:
      - /root/builds/${VER}:/export
      
    # Tell Ubuntu to copy the OpenWrt bin folder directly to your host
    command: >
      /bin/sh -c "
      cp -r /home/builder/openwrt/bin/* /export/ && 
      echo 'Success! Firmware exported to /root/builds/${VER}'"
